<?php

/**
 * @file
 * Provides Media RSS namespace, <channel> and <item> elements for Views RSS module.
 */

/**
 * Module installation path.
 */
define('VIEWS_RSS_MEDIA_PATH', drupal_get_path('module', 'views_rss_media'));

/**
 * Include file with field formatters.
 */
include_once VIEWS_RSS_MEDIA_PATH .'/views_rss_media.field.inc';

/**
 * Include file with all preprocess functions.
 */
include_once VIEWS_RSS_MEDIA_PATH .'/views_rss_media.inc';

/**
 * Implements hook_views_rss_namespaces().
 */
function views_rss_media_views_rss_namespaces() {
  $namespaces['media'] = array(
    'prefix' => 'xmlns',
    'uri' => 'http://search.yahoo.com/mrss/',
  );
  return $namespaces;
}

/**
 * Implements hook_views_rss_item_elements().
 */
function views_rss_media_views_rss_item_elements() {
  $elements['media:content'] = array(
    'description' => t(''),
    'preprocess functions' => array('views_rss_media_preprocess_item_content'),
    'help' => 'http://video.search.yahoo.com/mrss',
  );
  return $elements;
}